---
title: "Explore Ornithology KE EMu database"
output: html_document
date: "2022-10-11"
editor_options: 
  chunk_output_type: console
---

Load libraries
```{r}
library(tidyverse)
library(lubridate)
library(ggplot2)
```



First install flatfile of EMu database received from Bill at 9/16/2022

```{r}
data <- read.csv("Birds_Collection.csv")

data <- data %>% 
  select(Catalog.No, Field.No, Sex, LAF.No, Age, Spec.Nat, Measurements, Gonads, Weight, Collector, Date.Coll, Family, Genus, Species, Subspecies, Continent, Country, State, County, Township, Nearest.Named.Place) %>% 
  mutate(lacm = Catalog.No,
         field = Field.No,
         sex = Sex,
         laf = LAF.No,
         age = Age, 
         specnat = Spec.Nat,
         measure = Measurements,
         gonads = Gonads,
         wt = as.numeric(Weight),
         coll = Collector,
         datecoll = Date.Coll,
         species = paste(Genus, Species, sep = " "),
         spp = Subspecies,
         genus = Genus,
         family = Family,
         locality = paste(Country, State, County, Township, Nearest.Named.Place, sep = " "),
         state = State,
         county = County
         ) %>% 
  select(lacm, field, sex, laf, age, specnat, measure, gonads, wt, coll, datecoll, family, species, genus, spp, locality, state, county)


# transform date into an actual date category
data$date <- as.Date(data$datecoll, format="%d %B %Y")

min(data$date, na.rm=T)

data$year <- as.numeric(format(data$date, "%Y"))
data$month <- as.numeric(format(data$date, "%m"))

# remove odd dates
data2 <- data %>% filter(date > "1800-01-01")
```


Plot some trends
```{r}
sp <- "Buteo jamaicensis"

example <- data2 %>% filter(species == sp)

table(example$year, example$specnat)
hist(example$date, breaks=20)

example2 <- example %>% 
  filter(specnat == "SS" | specnat == "SN")
min(example2$year)
max(example2$year)

# Histogram based on specimen nature
ggplot(example2, aes(x = year, fill = specnat, color = specnat)) +
  geom_histogram(breaks = seq(1880, 2020, by = 10), alpha = 0.5, position="identity") +
  scale_x_continuous(breaks = seq(1880, 2020, 10)) +
  theme_classic() +
  labs(fill = "Specimen type", color = "Specimen type", x = "Year", y = "Count",
       title = sp)

# Histogram based on subspecies
ggplot(example2, aes(x = year, fill = spp, color = spp)) +
  geom_histogram(breaks = seq(1880, 2020, by = 10), alpha = 0.5, position="dodge2") +
  scale_x_continuous(breaks = seq(1880, 2020, 10)) +
  theme_classic() +
  labs(fill = "Subspecies", color = "Subspecies", x = "Year", y = "Count",
       title = sp)
```



Add map of specimen count by county/state

devtools::install_github("UrbanInstitute/urbnmapr")
```{r}
library(urbnmapr)

# plot states
states_sf <- get_urbn_map("states", sf = TRUE)

states_sf %>%
  ggplot() +
  geom_sf(aes(), 
          fill = "grey", color = "#ffffff", size = 0.25) +
  geom_sf_text(data = get_urbn_labels(map = "states", sf = TRUE), 
                aes(label = state_abbv), size = 3)

# plot counties
counties_sf <- get_urbn_map("counties", sf = TRUE)

counties_sf %>% 
  ggplot(aes()) +
  geom_sf(fill = "grey", color = "#ffffff")


### create summary by county/state
## by state
statecount <- example2 %>% 
  count(state) %>% 
  mutate(state2 = substr(state, 1, 2))

spat_state <- left_join(get_urbn_map(map = "states", sf = TRUE),
                         statecount,
                         by = c("state_name" = "state2"))

# plot count by state
ggplot() +
  geom_sf(spat_state,
          mapping = aes(fill = n),
          color = "#ffffff", size = 0.25) +
  labs(fill = "Specimen count") +
  labs(title = paste(sp, "by state", sep = " "))


## by county
countycount <- example2 %>% 
  count(state, county) %>% 
  mutate(state2 = substr(state, 1, 2)) %>% 
  mutate(statecounty = paste(state2, county, sep = "_"))

# need to capitalize and spell out County (County -> CO)
counties_sf$cty <- toupper(counties_sf$county_name)
counties_sf$cty2 <- gsub("COUNTY", "CO", counties_sf$cty)
counties_sf$statecounty <- paste(counties_sf$state_abbv, counties_sf$cty2, sep = "_")

# merge
spat_county <- left_join(counties_sf,
                         countycount,
                         by = "statecounty")
# plot count by county
ggplot() +
  geom_sf(spat_county,
          mapping = aes(fill = n),
          color = "#ffffff", size = 0.25) +
  labs(fill = "Count by county") +
  labs(title = paste(sp, "by county", sep = " "))

```

