---
title: "Untitled"
author: "YS"
date: "2024-02-01"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
#library(here)
library(tidyverse)
library(readxl)
library(stringi)
```

```{r}
setwd("C:/Users/young/Documents/nhm_ornithology/taxonomyupdate")
#here::i_am("taxonomyupdate.Rmd")
#here()
```

Load LACM list

```{r}
lacm <- read_excel("lacmtaxonomy.xlsx", col_names = c("catlog", "order", "family", "genus", "species", "subspecies", "rank", "sciname"), skip=1)

ltax <- unique(lacm$sciname) #5667; some subspecies don't have a species level entry

# make a fullname column
# first get all spp NA 
lacm$spp <- lacm$subspecies
lacm$spp[is.na(lacm$spp)] <- "NA"
lacm$spp[lacm$spp == "ssp"]  <- "NA" 

# concatenate for fullname 
lacm$fullname <- paste(lacm$genus, lacm$species, lacm$spp)


# get list of unique species + add family and order -> n=11119
lacmlist <- lacm[!duplicated(lacm[,"fullname"]),] %>% select(fullname, sciname, subspecies, genus, species, family, order)

#write.csv(lacmlist, "lacm_species_full.csv")


# new value for ssp=NA
lacmlist$subspecies[is.na(lacmlist$subspecies)] <- "NA"

# change ssp value to NA
lacmlist$subspecies[lacmlist$subspecies == "ssp"]  <- "NA" 

# change ssp value
lacmlist$fullname <- gsub("ssp", "NA", lacmlist$fullname)

n_distinct(lacmlist$fullname) #11119
```

Import translation key
```{r}
translat <- read_excel("peters_clements.xlsx")

translat$ct_pet <- stri_count(translat$peters, regex="\\S+")
translat$ct_clements <- stri_count(translat$clements, regex="\\S+")


## separate genus and species
# separate genus
translat$genus_pet <- sub(" .*", "", translat$peters)

# species needs to go on two turns [learn how to do it in one]
translat$species_pet <- sub(" [^ ]+$|^.*? ", "", translat$peters)
translat$species_pet <- sub(" .*", "", translat$species_pet)

# extract subspecies
translat$ssp_pet <- ifelse(translat$ct_pet == 3, sub(".* ", "", translat$peters), "NA")

# do same for clements
translat$genus_clements <- sub(" .*", "", translat$clements)
translat$species_clements <- sub(" [^ ]+$|^.*? ", "", translat$clements)
translat$species_clements <- sub(" .*", "", translat$species_clements)
translat$ssp_clements <- ifelse(translat$ct_clements == 3, sub(".* ", "", translat$clements), "NA")

# have full name
translat$full_clements <- paste(translat$genus_clements, translat$species_clements, translat$ssp_clements, sep = " ")
translat$full_pet <- paste(translat$genus_pet, translat$species_pet, translat$ssp_pet, sep = " ")

#save
#write.csv(translat, "translat.csv")
```


Join with original data set
```{r}
# left join - goes from 11539 to 11119
# how much of LACM species name matches old version assuming it is Peters
update0 <- lacmlist %>% 
  left_join(translat, by=c("fullname" = "full_pet")) %>% distinct(fullname, .keep_all = TRUE) %>% 
  select(fullname, family, order, full_clements, IOC_seq, family_clements, order_clements)

nrow(update0[is.na(update0$full_clements),]) #2106

n_distinct(lacmlist$fullname) #11119
n_distinct(update$fullname) #11119

# get part 1 without NAs
part1 <- update0[!is.na(update0$full_clements),] #9039 -> add all parts for 11119

rest1 <- update0[is.na(update0$full_clements),] %>% 
  select(-family_clements, -order_clements) #2080
  
#############
# next step
# with the ones without full_clements, merge with translat again now using clements
update1 <- rest1 %>% 
  select(-IOC_seq) %>% 
  left_join(translat, by=c("fullname" = "full_clements")) %>% 
  distinct(fullname, .keep_all = T) %>% 
  select(fullname, family, order, clements, IOC_seq, family_clements, order_clements)

nrow(update1[is.na(update1$clements),]) #1196

part2 <- update1[!is.na(update1$clements),] #884

rest2 <- update1[is.na(update1$clements),] #1196
 
#############
# next step
# manually checked with check_taxon.csv
# initially was from check4 %>% select(fullname, genus, species, subspecies, family, order)
# count varies slightly
checkcomp <- read.csv("check_taxon.csv")

update2 <- rest2 %>% 
  select(-order, -family) %>% 
  left_join(checkcomp, by="fullname") %>% 
  select(fullname, new_fullname, family, order) 


translat2 <- translat %>% 
  select(IOC_seq, ioc, clements, family_clements, order_clements)

checklast2 <- update2 %>% 
  left_join(translat2, by=c("new_fullname" = "clements")) %>% 
  distinct(new_fullname, .keep_all = T)


# still some that are NA
part3 <- checklast2[!is.na(checklast2$family_clements),] #974

rest3 <- checklast2[is.na(checklast2$family_clements),] #112

# merge finals with ioc
checklast3 <- rest3 %>% 
  select(-family_clements, -order_clements, -IOC_seq) %>% 
  left_join(translat2, by=c("new_fullname" = "ioc"))  %>% 
  distinct(new_fullname, .keep_all = T)
  
part4 <- checklast3[!is.na(checklast3$family_clements),] #38

rest4 <- checklast3[is.na(checklast3$family_clements),] #74

# rest are sp 
rest4$genus <- sub(" .*", "", rest4$new_fullname)
rest4.0 <- rest4 %>% 
  select(fullname, new_fullname, genus, family, order) %>%   
  left_join(translat, by = c("genus" = "genus_clements")) %>% 
  select(fullname, family, order, new_fullname, full_clements, family_clements, order_clements) %>% 
  distinct(new_fullname, .keep_all = T)
```


Merge all together
```{r}
part2.0 <- part2 %>% 
  mutate(full_clements = fullname) %>% 
  select(fullname, family, order, full_clements, IOC_seq, family_clements, order_clements)

# for part 3, make full_clements is missing so add
part3.0 <- part3 %>% 
  mutate(full_clements = new_fullname) %>% 
  select(fullname, family, order, full_clements, IOC_seq, family_clements, order_clements)

# for part 4, new_fullname becomes full_clements
# missing NA at the end for full_clements
# delete all NA at the fulldata set level
part4.0 <- part4 %>% 
  mutate(full_clements = new_fullname) %>% 
  select(fullname, family, order, full_clements, IOC_seq, family_clements, order_clements)

# last
rest4.1 <- rest4.0 %>% 
  select(-full_clements) %>% 
  mutate(full_clements = new_fullname,
         IOC_seq = NA) %>% 
  select(fullname, family, order, full_clements, IOC_seq, family_clements, order_clements)

# merge all 
fulldata <- rbind(part1, part2.0, part3.0, part4.0, rest4.1)

write.csv(fulldata, "fulldata.csv")
```



Next steps
```{r}
###########
# separate genus and species
upd$genus_clements <- sub(" .*", "", upd$clements)
upd$species_clements <- sub(" [^ ]+$|^.*? ", "", upd$clements)
upd$species_clements <- sub(" .*", "", upd$species_clements)


# how to deal with subspecies - noted as subspecies for EMu
upd$spp_clements <- ifelse(upd$io_rank == "ssp", sub(".* ", "", upd$clements), NA)

upd$name_match <- ifelse(upd$clements == upd$peters, "match", "no")
upd$genus_match <- ifelse(upd$genus_clements == upd$genus, "match", "no")
upd$species_match <- ifelse(upd$species_clements == upd$species, "match", "no")


upd2 <- upd %>% 
  mutate(emu_order = order,
         emu_family = family,
         emu_genus = genus,
         emu_species = species,
         emu_subspecies = subspecies,
         new_order = order_clements,
         new_family = family_clements,
         new_genus = genus_clements,
         new_species = species_clements)
  select(IOC_seq, emu_order, emu_family, emu_genus, emu_species, emu_subspecies, new_order, new_family, new_genus, new_species, )
```
